name: Build & Publish Release

on:
  push:
    tags:
      - "v*"   # v0.0.1 같은 태그 푸시할 때 실행

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Package & Publish with electron-builder
        run: npx electron-builder --${{ matrix.os == 'windows-latest' && 'win' || (matrix.os == 'macos-latest' && 'mac' || 'linux') }} --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
